GET http://localhost:5500/eventos
###
GET http://localhost:5500/proximos-eventos/2024-08-15

###

GET http://localhost:5500/estadisticas/eventos

###
POST http://localhost:5500/eventos
Content-Type: application/json

{"nombre": "Concierto de Rock",  "lugar": "Estadio Nacional", "fecha": "2024-12-15",}

###

POST http://localhost:5500/eventos
Content-Type: application/json

{"nombre": "Reunion", "lugar": "Facultad de tecnología", "fecha": "2024-10-15",}
